7.0.0 (#71)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,12 +1,8 @@
 name: "AdvancedOperation CI"
 
-concurrency: 
-  group: ${{ github.ref }}
-  cancel-in-progress: true
-
 on:
   schedule:
-    - cron:  '0 23 * * *' # At the end of every day
+    - cron: '0 0 * * 2' # Run every Tuesday
   push:
     branches:
       - main
@@ -16,12 +12,16 @@ on:
       - main
       - develop
 
+concurrency:
+  group: ${{ github.ref }}
+  cancel-in-progress: true
+
 jobs:
   info:
     name: Show macOS and Xcode versions
-    runs-on: macOS-12
+    runs-on: macos-14
     env:
-      DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer
+      DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
     steps:
       - name: stats
         run: |
@@ -33,87 +33,106 @@ jobs:
           brew info swiftlint
   macOS:
     name: Test macOS
-    runs-on: macOS-12
+    runs-on: macos-14
     env:
-      DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer
+      DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
       - name: macOS
-        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation macOS" -destination "platform=macOS" clean test -quiet -resultBundlePath '~/Downloads/Report/report.xcresult'
+        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation" -destination "platform=macOS" clean test -quiet -resultBundlePath '~/Downloads/Report/report.xcresult'
   iOS:
     name: Test iOS
-    runs-on: macOS-12
+    runs-on: macos-14
     env:
-      DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer
+      DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
     strategy:
       matrix:
-        destination: ["OS=16.0,name=iPhone 13 Pro"]
+        destination: ["OS=17.0,name=iPhone 15 Pro"]
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
       - name: iOS - ${{ matrix.destination }}
-        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation iOS" -destination "${{ matrix.destination }}" clean test -quiet -resultBundlePath '~/Downloads/Report/report.xcresult'
+        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation" -destination "${{ matrix.destination }}" clean test -quiet -resultBundlePath '~/Downloads/Report/report.xcresult'
 
       - name: Upload tests report
         if: ${{ always() }} # to run it only if the previous step fails use ${{ failure() }}
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v4
         with:
           name: iOS tests report
           path: ~/Downloads/Report 
-  tvOS:
-    name: Test tvOS
-    runs-on: macOS-12
+  visionOS:
+    name: Test visionOS
+    runs-on: macos-14
     env:
-      DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer
+      DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
     strategy:
       matrix:
-        destination: ["OS=16.0,name=Apple TV 4K (2nd generation)""]
+        destination: ["OS=1.0,name=Apple Vision Pro"]
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
+      - name: visionOS - ${{ matrix.destination }}
+        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation" -destination "${{ matrix.destination }}" clean test -quiet -resultBundlePath '~/Downloads/Report/report.xcresult'
+
+      - name: Upload tests report
+        if: ${{ always() }} # to run it only if the previous step fails use ${{ failure() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: visionOS tests report
+          path: ~/Downloads/Report
+  tvOS:
+    name: Test tvOS
+    runs-on: macos-14
+    env:
+      DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
+    strategy:
+      matrix:
+        destination: ["OS=17.0,name=Apple TV"]
+    steps:
+      - uses: actions/checkout@v4
       - name: tvOS - ${{ matrix.destination }}
-        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation tvOS" -destination "${{ matrix.destination }}" clean test -quiet -resultBundlePath '~/Downloads/Report/report.xcresult'
+        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation" -destination "${{ matrix.destination }}" clean test -quiet -resultBundlePath '~/Downloads/Report/report.xcresult'
       
       - name: Upload tests report
         if: ${{ always() }} # to run it only if the previous step fails use ${{ failure() }}
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v4
         with:
           name: tvOS tests report    
           path: ~/Downloads/Report       
   watchOS:
-    name: Build watchOS
-    runs-on: macOS-12
+    name: Test watchOS
+    runs-on: macos-14
     env:
-      DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer
+      DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
     strategy:
       matrix:
-        destination: ["OS=9.0,name=Apple Watch Series 8 (45mm)"]
+        destination: ["OS=10.0,name=Apple Watch Series 9 (45mm)"]
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
       - name: watchOS - ${{ matrix.destination }}
-        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation watchOS" -destination "${{ matrix.destination }}" clean test -quiet -resultBundlePath '~/Downloads/Report/report.xcresult'
+        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation" -destination "${{ matrix.destination }}" clean test -quiet -resultBundlePath '~/Downloads/Report/report.xcresult'
         
       - name: Upload tests report
         if: ${{ always() }} # to run it only if the previous step fails use ${{ failure() }}
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v4
         with:
           name: watchOS tests report
           path: ~/Downloads/Report
-  spm:
+  SPM:
     name: Test SPM Integration
-    runs-on: macOS-12
+    runs-on: macos-14
     env:
-      DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer
+      DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
       - name: SPM Test
         run: |
           swift --version
           swift test
-  lint:
-    name: Swift Lint
-    runs-on: macOS-12
-    steps:
-      - uses: actions/checkout@v2
-      - name: Run SwiftLint
-        run: |
-          swift --version
-          swiftlint --reporter github-actions-logging
+#  lint:
+#    name: Swift Lint
+#    runs-on: macos-14
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Run SwiftLint
+#        run: |
+#          swift --version
+#          swiftlint --reporter github-actions-logging
