update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,25 +40,25 @@ jobs:
       - uses: actions/checkout@v4
       - name: macOS
         run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation" -destination "platform=macOS" clean test -quiet -resultBundlePath '~/Downloads/Report/report.xcresult'
-#  iOS:
-#    name: Test iOS
-#    runs-on: macos-14
-#    env:
-#      DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
-#    strategy:
-#      matrix:
-#        destination: ["OS=16.0,name=iPhone 13 Pro"]
-#    steps:
-#      - uses: actions/checkout@v4
-#      - name: iOS - ${{ matrix.destination }}
-#        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation" -destination "${{ matrix.destination }}" clean test -quiet -resultBundlePath '~/Downloads/Report/report.xcresult'
-#
-#      - name: Upload tests report
-#        if: ${{ always() }} # to run it only if the previous step fails use ${{ failure() }}
-#        uses: actions/upload-artifact@v2
-#        with:
-#          name: iOS tests report
-#          path: ~/Downloads/Report 
+  iOS:
+    name: Test iOS
+    runs-on: macos-14
+    env:
+      DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
+    strategy:
+      matrix:
+        destination: ["OS=16.0,name=iPhone 15 Pro"]
+    steps:
+      - uses: actions/checkout@v4
+      - name: iOS - ${{ matrix.destination }}
+        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation" -destination "${{ matrix.destination }}" clean test -quiet -resultBundlePath '~/Downloads/Report/report.xcresult'
+
+      - name: Upload tests report
+        if: ${{ always() }} # to run it only if the previous step fails use ${{ failure() }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: iOS tests report
+          path: ~/Downloads/Report 
 #  tvOS:
 #    name: Test tvOS
 #    runs-on: macos-14
