added tests for watchOS

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -82,11 +82,18 @@ jobs:
       DEVELOPER_DIR: /Applications/Xcode_12.5.app/Contents/Developer
     strategy:
       matrix:
-        destination: ["OS=7.3,name=Apple Watch Series 5 - 44mm"]
+        destination: ["OS=7.4,name=Apple Watch Series 6 - 44mm"]
     steps:
       - uses: actions/checkout@v2
       - name: watchOS - ${{ matrix.destination }}
-        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation watchOS" -destination "${{ matrix.destination }}" clean build -quiet
+        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation watchOS" -destination "${{ matrix.destination }}" clean test -quiet -resultBundlePath '~/Downloads/Report/report.xcresult'
+        
+      - name: Upload tests report
+        if: ${{ always() }} # to run it only if the previous step fails use ${{ failure() }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: watchOS tests report
+          path: ~/Downloads/Report
   spm:
     name: Test SPM Integration
     runs-on: macos-11.0
